### ISSUE TITLE
New Mod Updates Crash on Startup

### ISSUE THREAD

**Issue by EmilyBZ** [defeatedcrow/HeatAndClimateMod#168]
Updated to Lib 3.3.5. and Mod 3.3.12 - Game Crashed on startup, tried to run with just HeatLib+HeatMod. Received same results.

Crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  DCASMPlugin (HeatAndClimateLib_1.12.2-3.3.5.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 8/1/20 10:14 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from HeatAndClimateMod (dcs_climate)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
	at defeatedcrow.hac.main.worldgen.vein.VeinTableJson.loadVeins(VeinTableJson.java:95)
	at defeatedcrow.hac.main.worldgen.vein.VeinTableJson.post(VeinTableJson.java:223)
	at defeatedcrow.hac.main.CommonMainProxy.loadWorldGenPost(CommonMainProxy.java:460)
	at defeatedcrow.hac.main.ClimateMain.postInit(ClimateMain.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 409178560 bytes (390 MB) / 1073741824 bytes (1024 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID          | Version      | Source                              | Signature                                |
	|:----- |:----------- |:------------ |:----------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft   | 1.12.2       | minecraft.jar                       | None                                     |
	| LCHIJ | mcp         | 9.42         | minecraft.jar                       | None                                     |
	| LCHIJ | FML         | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge       | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | dcs_asm     | 2.1.0        | minecraft.jar                       | 4cd12b92959105443b7b694fffe0cea9ed004886 |
	| LCHIJ | dcs_lib     | 3.3.5        | HeatAndClimateLib_1.12.2-3.3.5.jar  | 4cd12b92959105443b7b694fffe0cea9ed004886 |
	| LCHIE | dcs_climate | 3.3.12       | HeatAndClimateMod_1.12.2-3.3.12.jar | 4cd12b92959105443b7b694fffe0cea9ed004886 |

	Loaded coremods (and transformers): 
DCASMPlugin (HeatAndClimateLib_1.12.2-3.3.5.jar)
  defeatedcrow.hac.asm.DCMethodTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7637' Renderer: 'Intel(R) UHD Graphics 630'

**Comment by defeatedcrow** [comment]
This bug has been fixed in 1e3ba1f.
Thanks for the report!
