### ISSUE TITLE
Crash with Version 1.12.2-2.5.8

### ISSUE THREAD

**Issue by AdaraChristine** [defeatedcrow/HeatAndClimateMod#44]
Forge 14.23.4.2749
HeatAndClimateMod_1.12.2-2.5.8
HeatAndClimateLib_1.12.2-2.5.7

Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from HeatAndClimateMod (dcs_climate)
Caused by: java.lang.NullPointerException
	at net.minecraftforge.client.model.ModelLoader.setCustomModelResourceLocation(ModelLoader.java:1090)
	at defeatedcrow.hac.core.client.JsonRegisterHelper.regSimpleItem(JsonRegisterHelper.java:58)
	at defeatedcrow.hac.main.client.JsonRegister.regTools(JsonRegister.java:203)
	at defeatedcrow.hac.main.client.JsonRegister.load(JsonRegister.java:23)
	at defeatedcrow.hac.main.client.ClientMainProxy.loadMaterial(ClientMainProxy.java:134)
	at defeatedcrow.hac.main.ClimateMain.preInit(ClimateMain.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)

https://pastebin.com/wmbB3gdB

**Comment by defeatedcrow** [comment]
Thanks for the report!
It fixed at https://github.com/defeatedcrow/HeatAndClimateLib/commit/683832d339fbc1e71e8bfdc6168dab367ca78d71 and b4a8c94.
