### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by AdaraChristine** [defeatedcrow/HeatAndClimateMod#47]
Forge 14.23.4.2749
HeatAndClimateLib_1.12.2-2.5.8
HeatAndClimateMod_1.12.2-2.5.10

Time: 9/3/18 6:35 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at defeatedcrow.hac.main.worldgen.CaravanGenEvent.getRondomContainer1(CaravanGenEvent.java:253)
	at defeatedcrow.hac.main.worldgen.CaravanGenEvent.updateInterior1(CaravanGenEvent.java:223)
	at defeatedcrow.hac.main.worldgen.CaravanGenEvent.onLoad(CaravanGenEvent.java:130)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1525_CaravanGenEvent_onLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:860)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
https://pastebin.com/dHTKJFvh

**Comment by defeatedcrow** [comment]
It fixed in 2e0ef78. thank you!
