### ISSUE TITLE
Ancient Warfare 2 and Windmill worldgen crash

### ISSUE THREAD

**Issue by AdaraChristine** [defeatedcrow/HeatAndClimateMod#66]
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at defeatedcrow.hac.main.worldgen.WorldGenWindmill.generate(WorldGenWindmill.java:255)
	at defeatedcrow.hac.main.worldgen.WorldGenWindmill.generateWindmill(WorldGenWindmill.java:137)
	at defeatedcrow.hac.main.worldgen.WorldGenWindmill.generate(WorldGenWindmill.java:57)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at net.shadowmage.ancientwarfare.structure.worldgen.WorldStructureGenerator.getTargetY(WorldStructureGenerator.java:101)
	at net.shadowmage.ancientwarfare.structure.template.build.validation.StructureValidator.underFill(StructureValidator.java:543)
	at net.shadowmage.ancientwarfare.structure.template.build.validation.StructureValidator.prePlacementUnderfill(StructureValidator.java:559)
	at net.shadowmage.ancientwarfare.structure.template.build.validation.StructureValidatorGround.preGeneration(StructureValidatorGround.java:44)
	at net.shadowmage.ancientwarfare.structure.template.build.StructureBuilderWorldGen.instantConstruction(StructureBuilderWorldGen.java:16)
	at net.shadowmage.ancientwarfare.structure.worldgen.WorldGenTickHandler$StructureGenerationTicket.call(WorldGenTickHandler.java:146)
	at net.shadowmage.ancientwarfare.structure.worldgen.WorldGenTickHandler.genStructures(WorldGenTickHandler.java:101)
	at net.shadowmage.ancientwarfare.structure.worldgen.WorldGenTickHandler.serverTick(WorldGenTickHandler.java:54)
https://pastebin.com/N2qeT1R1

**Comment by defeatedcrow** [comment]
It was fixed in 69a9894. Thank you!
